/**
 * Export Service
 * Handles exporting project outputs as Markdown files.
 * Source ZIP export is handled by packageService.
 */

import { Project, CompiledOutput, Agent } from '../types';

/**
 * Generates a Markdown export of the full project.
 */
export function generateMarkdownExport(
  project: Project,
  compiledOutput: CompiledOutput,
  agents: Agent[]
): string {
  const exportDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const workflowLabel: Record<string, string> = {
    website: 'Website Builder',
    startup: 'Startup Builder',
    student: 'Student Project Builder',
    custom: 'Custom Workflow',
  };

  const header = `---
title: "${project.title}"
workflow: "${workflowLabel[project.workflow_type] || project.workflow_type}"
generated_by: "FRIENDS — Framework for Rapid Intelligent Execution, Networking, Design, and Strategy"
generated_at: "${exportDate}"
status: "${project.status}"
---

`;

  const tableOfContents = `# Table of Contents

1. [Project Overview](#project-overview)
2. [Compiled Final Output](#compiled-final-output)
3. [Individual Agent Outputs](#individual-agent-outputs)
   ${agents
     .filter((a) => a.status === 'completed')
     .map((a, i) => `${i + 3}. [${a.name} — ${a.role}](#${slugify(a.name)})`)
     .join('\n   ')}

---

`;

  const projectOverview = `# Project Overview

- **Title**: ${project.title}
- **Workflow**: ${workflowLabel[project.workflow_type] || project.workflow_type}
- **Description**: ${project.description}
- **Generated**: ${exportDate}
- **Agents Used**: ${agents.length}
- **Status**: ${project.status}

${
  project.clarifications && project.clarifications.length > 0
    ? `## Project Context

${project.clarifications.map((qa) => `**Q**: ${qa.question}\n**A**: ${qa.answer}`).join('\n\n')}`
    : ''
}

---

`;

  const compiledSection = `# Compiled Final Output

${compiledOutput.content}

---

`;

  const agentOutputsSection = `# Individual Agent Outputs

${agents
  .filter((a) => a.status === 'completed' && a.output)
  .sort((a, b) => a.order_index - b.order_index)
  .map(
    (agent) => `## ${agent.name} — ${agent.role}

**Task**: ${agent.task}

**Expected Output**: ${agent.expected_output}

---

${agent.output}

---
`
  )
  .join('\n\n')}`;

  const footer = `
---

*Generated by [FRIENDS](https://github.com/friends-ai) — Your AI team that turns ideas into complete projects.*
*Framework for Rapid Intelligent Execution, Networking, Design, and Strategy*
`;

  return header + tableOfContents + projectOverview + compiledSection + agentOutputsSection + footer;
}

/**
 * Converts a string to a URL-friendly slug for anchor links.
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}
