export type TemplateId =
  | 'ai_chatbot'
  | 'pdf_to_notes_converter'
  | 'ambulance_tracker'
  | 'attendance_portal'
  | 'bmi_calculator'
  | 'expense_tracker'
  | 'generic_web_app';

export type ProjectType =
  | 'Auto-detect'
  | 'Website'
  | 'Functional Web App'
  | 'Dashboard'
  | 'AI Tool'
  | 'Startup Builder'
  | 'Student Project';

export type ValidationRules = {
  requiredFiles: string[];
  requiredText: string[];
  forbiddenText: string[];
};

export type ProjectTemplate = {
  id: TemplateId;
  name: string;
  intentProjectType: string;
  domain: string;
  projectType: ProjectType;
  description: string;
  matchKeywords: string[];
  negativeKeywords?: string[];
  features: string[];
  components: string[];
  logic: string[];
  forbiddenMistakes: string[];
  previewBullets: string[];
  validation: ValidationRules;
  files: Record<string, string>;
};

const nextPackage = (name: string) =>
  JSON.stringify(
    {
      name,
      version: '1.0.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
      },
      dependencies: {
        '@tailwindcss/postcss': 'latest',
        '@types/node': 'latest',
        '@types/react': 'latest',
        '@types/react-dom': 'latest',
        next: 'latest',
        postcss: 'latest',
        react: 'latest',
        'react-dom': 'latest',
        tailwindcss: 'latest',
        typescript: 'latest',
        'lucide-react': 'latest',
      },
      devDependencies: {},
    },
    null,
    2,
  );

const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;
`;

const tsConfig = JSON.stringify(
  {
    compilerOptions: {
      target: 'es5',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  },
  null,
  2,
);

const tailwindConfig = `import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`;

const postcssConfig = `export default {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
`;

const layoutFile = (title: string) => `import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: '${title}',
  description: 'Generated by FRIENDS as a standalone runnable project.',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

const globalsCss = `@import "tailwindcss";

:root {
  color: #0f172a;
  background: #f8fafc;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

button,
input,
select {
  font: inherit;
}
`;

function baseNextFiles(name: string, pageComponent: string, readme: string): Record<string, string> {
  return {
    'package.json': nextPackage(name.toLowerCase().replace(/[^a-z0-9]+/g, '-')),
    'next.config.js': nextConfig,
    'tsconfig.json': tsConfig,
    'tailwind.config.ts': tailwindConfig,
    'postcss.config.mjs': postcssConfig,
    'app/layout.tsx': layoutFile(name),
    'app/page.tsx': pageComponent,
    'app/globals.css': globalsCss,
    'README.md': readme,
  };
}

const expenseFiles: Record<string, string> = {
  ...baseNextFiles(
    'Expense Tracker',
    `import { ExpenseTracker } from '@/components/ExpenseTracker';

export default function HomePage() {
  return <ExpenseTracker />;
}
`,
    `# Expense Tracker

A standalone personal finance dashboard generated by FRIENDS.

## Features

- Add income and expense transactions
- Track title, amount, category, date, and type
- View total income, total expenses, and current balance
- Filter transactions by type and category
- Delete transactions
- Empty state and validation errors
- Local state persistence in the browser

## Run

\`\`\`bash
npm install
npm run dev
\`\`\`
`,
  ),
  'types/finance.ts': `export type TransactionType = 'income' | 'expense';

export type Transaction = {
  id: string;
  title: string;
  amount: number;
  category: string;
  date: string;
  type: TransactionType;
};

export type TransactionFilters = {
  type: 'all' | TransactionType;
  category: string;
};
`,
  'lib/finance.ts': `import type { Transaction, TransactionFilters } from '@/types/finance';

export function calculateIncome(transactions: Transaction[]) {
  return transactions
    .filter((transaction) => transaction.type === 'income')
    .reduce((total, transaction) => total + transaction.amount, 0);
}

export function calculateExpenses(transactions: Transaction[]) {
  return transactions
    .filter((transaction) => transaction.type === 'expense')
    .reduce((total, transaction) => total + transaction.amount, 0);
}

export function calculateBalance(transactions: Transaction[]) {
  return calculateIncome(transactions) - calculateExpenses(transactions);
}

export function addTransaction(transactions: Transaction[], transaction: Transaction) {
  return [transaction, ...transactions];
}

export function deleteTransaction(transactions: Transaction[], id: string) {
  return transactions.filter((transaction) => transaction.id !== id);
}

export function filterTransactions(transactions: Transaction[], filters: TransactionFilters) {
  return transactions.filter((transaction) => {
    const typeMatches = filters.type === 'all' || transaction.type === filters.type;
    const categoryMatches = filters.category === 'all' || transaction.category === filters.category;
    return typeMatches && categoryMatches;
  });
}
`,
  'lib/mockTransactions.ts': `import type { Transaction } from '@/types/finance';

export const mockTransactions: Transaction[] = [
  { id: 'txn-1', title: 'Salary', amount: 68000, category: 'Salary', date: '2026-05-01', type: 'income' },
  { id: 'txn-2', title: 'Groceries', amount: 4200, category: 'Food', date: '2026-05-04', type: 'expense' },
  { id: 'txn-3', title: 'Freelance project', amount: 12000, category: 'Freelance', date: '2026-05-08', type: 'income' },
  { id: 'txn-4', title: 'Metro pass', amount: 1500, category: 'Transport', date: '2026-05-11', type: 'expense' },
];
`,
  'components/ExpenseTracker.tsx': `'use client';

import { useEffect, useMemo, useState } from 'react';
import { CategoryFilter } from '@/components/CategoryFilter';
import { EmptyState } from '@/components/EmptyState';
import { Footer } from '@/components/Footer';
import { SummaryCards } from '@/components/SummaryCards';
import { TransactionForm } from '@/components/TransactionForm';
import { TransactionList } from '@/components/TransactionList';
import { calculateBalance, calculateExpenses, calculateIncome, deleteTransaction, filterTransactions } from '@/lib/finance';
import { mockTransactions } from '@/lib/mockTransactions';
import type { Transaction, TransactionFilters } from '@/types/finance';

const storageKey = 'friends-expense-tracker-transactions';

export function ExpenseTracker() {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [filters, setFilters] = useState<TransactionFilters>({ type: 'all', category: 'all' });
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const saved = window.localStorage.getItem(storageKey);
    setTransactions(saved ? JSON.parse(saved) : mockTransactions);
    setLoaded(true);
  }, []);

  useEffect(() => {
    if (loaded) window.localStorage.setItem(storageKey, JSON.stringify(transactions));
  }, [loaded, transactions]);

  const categories = useMemo(() => Array.from(new Set(transactions.map((transaction) => transaction.category))).sort(), [transactions]);
  const filteredTransactions = useMemo(() => filterTransactions(transactions, filters), [transactions, filters]);

  function handleAddTransaction(transaction: Transaction) {
    setTransactions((current) => [transaction, ...current]);
  }

  function handleDeleteTransaction(id: string) {
    setTransactions((current) => deleteTransaction(current, id));
  }

  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
        <div className="mb-8 rounded-[32px] border border-white/10 bg-gradient-to-br from-slate-900 to-slate-800 p-6 shadow-2xl">
          <p className="text-sm font-bold uppercase tracking-[0.2em] text-emerald-300">Personal finance dashboard</p>
          <h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">Expense Tracker</h1>
          <p className="mt-4 max-w-2xl text-slate-300">
            Add transactions, monitor income and expenses, filter by category, and keep your current balance visible.
          </p>
        </div>

        <SummaryCards
          income={calculateIncome(transactions)}
          expenses={calculateExpenses(transactions)}
          balance={calculateBalance(transactions)}
        />

        <div className="mt-6 grid gap-6 lg:grid-cols-[420px_1fr]">
          <TransactionForm onAddTransaction={handleAddTransaction} />
          <section className="rounded-3xl border border-white/10 bg-white/[0.06] p-5 backdrop-blur">
            <CategoryFilter filters={filters} categories={categories} onChange={setFilters} />
            {filteredTransactions.length === 0 ? (
              <EmptyState />
            ) : (
              <TransactionList transactions={filteredTransactions} onDeleteTransaction={handleDeleteTransaction} />
            )}
          </section>
        </div>
      </section>
      <Footer />
    </main>
  );
}
`,
  'components/TransactionForm.tsx': `'use client';

import { useState } from 'react';
import type { Transaction, TransactionType } from '@/types/finance';

type TransactionFormProps = {
  onAddTransaction: (transaction: Transaction) => void;
};

export function TransactionForm({ onAddTransaction }: TransactionFormProps) {
  const [title, setTitle] = useState('');
  const [amount, setAmount] = useState('');
  const [category, setCategory] = useState('Food');
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [type, setType] = useState<TransactionType>('expense');
  const [error, setError] = useState('');

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const numericAmount = Number(amount);

    if (!title.trim()) {
      setError('Enter a transaction title.');
      return;
    }
    if (!numericAmount || numericAmount <= 0) {
      setError('Enter a valid amount.');
      return;
    }

    onAddTransaction({
      id: crypto.randomUUID(),
      title: title.trim(),
      amount: numericAmount,
      category,
      date,
      type,
    });

    setTitle('');
    setAmount('');
    setCategory('Food');
    setType('expense');
    setError('');
  }

  return (
    <form onSubmit={handleSubmit} className="rounded-3xl border border-white/10 bg-white/[0.06] p-5 backdrop-blur">
      <h2 className="text-xl font-black">Add Transaction</h2>
      <div className="mt-5 space-y-4">
        <label className="grid gap-2 text-sm font-bold text-slate-300">
          Title
          <input value={title} onChange={(event) => setTitle(event.target.value)} className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-white outline-none focus:border-violet-400" />
        </label>
        <label className="grid gap-2 text-sm font-bold text-slate-300">
          Amount
          <input value={amount} type="number" onChange={(event) => setAmount(event.target.value)} className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-white outline-none focus:border-violet-400" />
        </label>
        <div className="grid gap-4 sm:grid-cols-2">
          <label className="grid gap-2 text-sm font-bold text-slate-300">
            Category
            <select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-white outline-none focus:border-violet-400">
              <option>Food</option>
              <option>Transport</option>
              <option>Salary</option>
              <option>Freelance</option>
              <option>Shopping</option>
              <option>Bills</option>
            </select>
          </label>
          <label className="grid gap-2 text-sm font-bold text-slate-300">
            Date
            <input value={date} type="date" onChange={(event) => setDate(event.target.value)} className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-white outline-none focus:border-violet-400" />
          </label>
        </div>
        <div className="grid grid-cols-2 gap-2">
          {(['income', 'expense'] as TransactionType[]).map((option) => (
            <button key={option} type="button" onClick={() => setType(option)} className={\`rounded-2xl border px-4 py-3 font-black capitalize \${type === option ? 'border-violet-400 bg-violet-500 text-white' : 'border-white/10 bg-slate-950 text-slate-300'}\`}>
              {option}
            </button>
          ))}
        </div>
        {error ? <p className="rounded-2xl border border-red-400/30 bg-red-500/10 px-4 py-3 text-sm font-bold text-red-200">{error}</p> : null}
        <button type="submit" className="w-full rounded-2xl bg-violet-500 px-5 py-4 font-black text-white hover:bg-violet-400">
          Add Transaction
        </button>
      </div>
    </form>
  );
}
`,
  'components/SummaryCards.tsx': `type SummaryCardsProps = {
  income: number;
  expenses: number;
  balance: number;
};

export function SummaryCards({ income, expenses, balance }: SummaryCardsProps) {
  const cards = [
    { label: 'Total Income', value: income, tone: 'text-emerald-300' },
    { label: 'Total Expenses', value: expenses, tone: 'text-rose-300' },
    { label: 'Current Balance', value: balance, tone: balance >= 0 ? 'text-cyan-300' : 'text-amber-300' },
  ];

  return (
    <section className="grid gap-4 md:grid-cols-3">
      {cards.map((card) => (
        <article key={card.label} className="rounded-3xl border border-white/10 bg-white/[0.06] p-5 backdrop-blur">
          <p className="text-sm font-bold text-slate-400">{card.label}</p>
          <p className={\`mt-2 text-3xl font-black \${card.tone}\`}>₹{card.value.toLocaleString('en-IN')}</p>
        </article>
      ))}
    </section>
  );
}
`,
  'components/TransactionList.tsx': `import { TransactionItem } from '@/components/TransactionItem';
import type { Transaction } from '@/types/finance';

type TransactionListProps = {
  transactions: Transaction[];
  onDeleteTransaction: (id: string) => void;
};

export function TransactionList({ transactions, onDeleteTransaction }: TransactionListProps) {
  return (
    <div className="mt-5 space-y-3">
      {transactions.map((transaction) => (
        <TransactionItem key={transaction.id} transaction={transaction} onDeleteTransaction={onDeleteTransaction} />
      ))}
    </div>
  );
}
`,
  'components/TransactionItem.tsx': `import type { Transaction } from '@/types/finance';

type TransactionItemProps = {
  transaction: Transaction;
  onDeleteTransaction: (id: string) => void;
};

export function TransactionItem({ transaction, onDeleteTransaction }: TransactionItemProps) {
  const isIncome = transaction.type === 'income';

  return (
    <article className="grid gap-3 rounded-2xl border border-white/10 bg-slate-950/80 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center">
      <div>
        <h3 className="font-black text-white">{transaction.title}</h3>
        <p className="mt-1 text-sm text-slate-400">{transaction.category} · {transaction.date}</p>
      </div>
      <p className={\`font-black \${isIncome ? 'text-emerald-300' : 'text-rose-300'}\`}>
        {isIncome ? '+' : '-'}₹{transaction.amount.toLocaleString('en-IN')}
      </p>
      <button onClick={() => onDeleteTransaction(transaction.id)} className="rounded-xl border border-white/10 px-3 py-2 text-sm font-bold text-slate-300 hover:border-red-300/40 hover:text-red-200">
        Delete Transaction
      </button>
    </article>
  );
}
`,
  'components/CategoryFilter.tsx': `import type { TransactionFilters } from '@/types/finance';

type CategoryFilterProps = {
  filters: TransactionFilters;
  categories: string[];
  onChange: (filters: TransactionFilters) => void;
};

export function CategoryFilter({ filters, categories, onChange }: CategoryFilterProps) {
  return (
    <div className="grid gap-3 sm:grid-cols-2">
      <label className="grid gap-2 text-sm font-bold text-slate-300">
        Type
        <select value={filters.type} onChange={(event) => onChange({ ...filters, type: event.target.value as TransactionFilters['type'] })} className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-white">
          <option value="all">All transactions</option>
          <option value="income">Income</option>
          <option value="expense">Expense</option>
        </select>
      </label>
      <label className="grid gap-2 text-sm font-bold text-slate-300">
        Category
        <select value={filters.category} onChange={(event) => onChange({ ...filters, category: event.target.value })} className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-white">
          <option value="all">All categories</option>
          {categories.map((category) => <option key={category} value={category}>{category}</option>)}
        </select>
      </label>
    </div>
  );
}
`,
  'components/EmptyState.tsx': `export function EmptyState() {
  return (
    <div className="mt-5 rounded-3xl border border-dashed border-white/20 bg-slate-950/70 p-8 text-center">
      <h3 className="text-lg font-black text-white">No transactions found</h3>
      <p className="mt-2 text-sm text-slate-400">Adjust your filters or add a transaction to start tracking your balance.</p>
    </div>
  );
}
`,
  'components/Footer.tsx': `export function Footer() {
  return (
    <footer className="px-4 pb-8 text-center text-sm text-slate-500">
      Expense Tracker generated by FRIENDS.
    </footer>
  );
}
`,
};

const ambulanceFiles: Record<string, string> = {
  ...baseNextFiles(
    'Ambulance Tracker',
    `import { AmbulanceTracker } from '@/components/AmbulanceTracker';

export default function HomePage() {
  return <AmbulanceTracker />;
}
`,
    `# Ambulance Tracker

Standalone emergency dispatch prototype generated by FRIENDS.

## Run

\`\`\`bash
npm install
npm run dev
\`\`\`
`,
  ),
  'components/AmbulanceTracker.tsx': `'use client';

import { useMemo, useState } from 'react';
import { AmbulanceList } from '@/components/AmbulanceList';
import { MapPanel } from '@/components/MapPanel';
import { mockAmbulances } from '@/lib/mockAmbulances';

export function AmbulanceTracker() {
  const [query, setQuery] = useState('');
  const nearbyAmbulances = useMemo(
    () => mockAmbulances.filter((ambulance) => ambulance.area.toLowerCase().includes(query.toLowerCase()) || ambulance.id.toLowerCase().includes(query.toLowerCase())),
    [query],
  );

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-8 text-white">
      <section className="mx-auto max-w-6xl">
        <div className="mb-6 rounded-3xl border border-white/10 bg-white/[0.06] p-6">
          <p className="text-sm font-bold uppercase tracking-[0.2em] text-cyan-300">Emergency dispatch</p>
          <h1 className="mt-3 text-5xl font-black">Ambulance Tracker</h1>
          <p className="mt-3 text-slate-300">Track nearby ambulances, ETA, availability, and contact routes.</p>
        </div>
        <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search location or ambulance ID" className="mb-6 w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3" />
        <div className="grid gap-6 lg:grid-cols-[1fr_380px]">
          <AmbulanceList ambulances={nearbyAmbulances} />
          <MapPanel ambulances={nearbyAmbulances} />
        </div>
      </section>
    </main>
  );
}
`,
  'components/AmbulanceList.tsx': `import type { AmbulanceUnit } from '@/lib/mockAmbulances';

export function AmbulanceList({ ambulances }: { ambulances: AmbulanceUnit[] }) {
  return (
    <section className="space-y-3">
      {ambulances.map((ambulance) => (
        <article key={ambulance.id} className="rounded-3xl border border-white/10 bg-white/[0.06] p-5">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h2 className="text-xl font-black">{ambulance.id}</h2>
              <p className="text-slate-400">{ambulance.area}</p>
            </div>
            <div className="grid grid-cols-3 gap-2 text-center text-sm">
              <strong>{ambulance.distance} km</strong>
              <strong>{ambulance.eta} min ETA</strong>
              <strong>{ambulance.status}</strong>
            </div>
          </div>
        </article>
      ))}
    </section>
  );
}
`,
  'components/MapPanel.tsx': `import type { AmbulanceUnit } from '@/lib/mockAmbulances';

export function MapPanel({ ambulances }: { ambulances: AmbulanceUnit[] }) {
  return (
    <aside className="rounded-3xl border border-white/10 bg-cyan-500/10 p-5">
      <h2 className="text-xl font-black">Map Panel</h2>
      <p className="mt-2 text-sm text-slate-300">Prototype location panel for nearby ambulance coverage.</p>
      <div className="mt-5 space-y-2">
        {ambulances.map((ambulance) => (
          <div key={ambulance.id} className="rounded-2xl bg-slate-950/70 px-4 py-3 text-sm">
            {ambulance.id}: {ambulance.area}
          </div>
        ))}
      </div>
    </aside>
  );
}
`,
  'lib/mockAmbulances.ts': `export type AmbulanceUnit = {
  id: string;
  area: string;
  distance: number;
  eta: number;
  status: 'Available' | 'Busy';
};

export const mockAmbulances: AmbulanceUnit[] = [
  { id: 'AMB-102', area: 'Central Hospital', distance: 1.2, eta: 4, status: 'Available' },
  { id: 'AMB-214', area: 'Ring Road Clinic', distance: 2.8, eta: 9, status: 'Available' },
  { id: 'AMB-330', area: 'City Trauma Care', distance: 4.6, eta: 14, status: 'Busy' },
];
`,
};

const pdfFiles: Record<string, string> = {
  ...baseNextFiles(
    'PDF Notes Converter',
    `import { PdfNotesConverter } from '@/components/PdfNotesConverter';

export default function HomePage() {
  return <PdfNotesConverter />;
}
`,
    `# PDF Notes Converter

Standalone notes generator template exported by FRIENDS.
`,
  ),
  'components/PdfNotesConverter.tsx': `'use client';

import { useMemo, useState } from 'react';

export function PdfNotesConverter() {
  const [source, setSource] = useState('');
  const notes = useMemo(() => source.split(/[.!?]/).map((item) => item.trim()).filter(Boolean).slice(0, 6), [source]);

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-8 text-white">
      <section className="mx-auto max-w-5xl rounded-3xl border border-white/10 bg-white/[0.06] p-6">
        <p className="text-sm font-bold uppercase tracking-[0.2em] text-violet-300">Study tool</p>
        <h1 className="mt-3 text-5xl font-black">PDF Notes Converter</h1>
        <p className="mt-3 text-slate-300">Paste extracted document text and convert it into structured notes.</p>
        <textarea value={source} onChange={(event) => setSource(event.target.value)} className="mt-6 min-h-56 w-full rounded-2xl border border-white/10 bg-slate-900 p-4" />
        <h2 className="mt-6 text-2xl font-black">Generated Notes</h2>
        <ul className="mt-3 space-y-2">{notes.map((note) => <li key={note} className="rounded-xl bg-slate-900 p-3">{note}</li>)}</ul>
      </section>
    </main>
  );
}
`,
};

const aiChatbotFiles: Record<string, string> = {
  ...baseNextFiles(
    'AI Chatbot',
    `import { Chatbot } from '@/components/Chatbot';

export default function HomePage() {
  return <Chatbot />;
}
`,
    `# AI Chatbot

A standalone AI chatbot interface generated by FRIENDS.

## Features

- Prompt input and chat history
- Mock assistant responses when no API key is configured
- Suggested prompts
- Responsive dark SaaS UI
- Local message state

## Run

\`\`\`bash
npm install
npm run dev
npm run build
\`\`\`
`,
  ),
  'types/chat.ts': `export type ChatRole = 'user' | 'assistant';

export type ChatMessage = {
  id: string;
  role: ChatRole;
  content: string;
  createdAt: string;
};
`,
  'lib/mockAssistant.ts': `import type { ChatMessage } from '@/types/chat';

export function createAssistantReply(input: string): ChatMessage {
  const topic = input.trim() || 'your idea';

  return {
    id: crypto.randomUUID(),
    role: 'assistant',
    content: \`Here is a focused response about "\${topic}". I can help turn this into requirements, code tasks, UX flows, or a launch checklist.\`,
    createdAt: new Date().toISOString(),
  };
}
`,
  'components/Chatbot.tsx': `'use client';

import { useMemo, useState } from 'react';
import { Bot, Send, Sparkles } from 'lucide-react';
import { ChatMessageList } from '@/components/ChatMessageList';
import { PromptSuggestions } from '@/components/PromptSuggestions';
import { createAssistantReply } from '@/lib/mockAssistant';
import type { ChatMessage } from '@/types/chat';

const initialMessages: ChatMessage[] = [
  {
    id: 'welcome',
    role: 'assistant',
    content: 'Hi, I am your AI chatbot. Ask me to brainstorm, explain, summarize, or plan something.',
    createdAt: new Date().toISOString(),
  },
];

export function Chatbot() {
  const [messages, setMessages] = useState<ChatMessage[]>(initialMessages);
  const [input, setInput] = useState('');
  const [error, setError] = useState('');

  const latestTopic = useMemo(() => messages.filter((message) => message.role === 'user').at(-1)?.content || 'No prompt yet', [messages]);

  function sendMessage(messageText = input) {
    const content = messageText.trim();
    if (!content) {
      setError('Enter a message before sending.');
      return;
    }

    const userMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: 'user',
      content,
      createdAt: new Date().toISOString(),
    };

    setMessages((current) => [...current, userMessage, createAssistantReply(content)]);
    setInput('');
    setError('');
  }

  return (
    <main className="min-h-screen bg-[#050510] px-4 py-8 text-white">
      <section className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[1fr_360px]">
        <div className="rounded-[32px] border border-white/10 bg-white/[0.06] p-5 shadow-2xl backdrop-blur">
          <div className="mb-6 flex items-start justify-between gap-4">
            <div>
              <p className="inline-flex items-center gap-2 text-sm font-black uppercase tracking-[0.2em] text-cyan-300">
                <Bot className="h-4 w-4" /> AI Chatbot
              </p>
              <h1 className="mt-3 text-4xl font-black sm:text-6xl">Chat with your AI assistant.</h1>
              <p className="mt-3 max-w-2xl text-slate-300">Ask questions, generate plans, and keep a clean conversation history.</p>
            </div>
            <Sparkles className="h-6 w-6 text-violet-300" />
          </div>

          <ChatMessageList messages={messages} />

          <div className="mt-5 rounded-3xl border border-white/10 bg-slate-950/80 p-3">
            <textarea
              value={input}
              onChange={(event) => setInput(event.target.value)}
              placeholder="Ask the chatbot anything..."
              className="min-h-28 w-full resize-y rounded-2xl border border-white/10 bg-[#090B1A] p-4 text-white outline-none placeholder:text-slate-500 focus:border-violet-400"
            />
            {error ? <p className="px-2 py-2 text-sm font-bold text-red-300">{error}</p> : null}
            <button onClick={() => sendMessage()} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-violet-600 px-5 py-4 font-black text-white hover:bg-violet-500">
              <Send className="h-4 w-4" /> Send Message
            </button>
          </div>
        </div>

        <aside className="rounded-[32px] border border-white/10 bg-white/[0.06] p-5 backdrop-blur">
          <h2 className="text-xl font-black">Prompt Suggestions</h2>
          <PromptSuggestions onSelect={sendMessage} />
          <div className="mt-6 rounded-2xl border border-white/10 bg-slate-950/70 p-4">
            <p className="text-sm font-bold text-slate-400">Latest topic</p>
            <p className="mt-2 text-white">{latestTopic}</p>
          </div>
        </aside>
      </section>
    </main>
  );
}
`,
  'components/ChatMessageList.tsx': `import type { ChatMessage } from '@/types/chat';

export function ChatMessageList({ messages }: { messages: ChatMessage[] }) {
  return (
    <div className="space-y-3">
      {messages.map((message) => (
        <article
          key={message.id}
          className={\`rounded-3xl border p-4 \${message.role === 'assistant' ? 'border-violet-300/20 bg-violet-500/10' : 'border-cyan-300/20 bg-cyan-400/10'}\`}
        >
          <p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">{message.role}</p>
          <p className="mt-2 leading-7 text-slate-100">{message.content}</p>
        </article>
      ))}
    </div>
  );
}
`,
  'components/PromptSuggestions.tsx': `const suggestions = [
  'Summarize this idea into product requirements',
  'Create a launch checklist for my SaaS',
  'Explain this concept like I am a beginner',
  'Draft a project plan for a weekend build',
];

export function PromptSuggestions({ onSelect }: { onSelect: (prompt: string) => void }) {
  return (
    <div className="mt-4 space-y-2">
      {suggestions.map((suggestion) => (
        <button
          key={suggestion}
          onClick={() => onSelect(suggestion)}
          className="w-full rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3 text-left text-sm font-bold text-slate-300 hover:border-violet-300/40 hover:text-white"
        >
          {suggestion}
        </button>
      ))}
    </div>
  );
}
`,
};

const attendanceFiles = baseNextFiles(
  'Student Attendance Portal',
  `export default function HomePage() {
  return (
    <main className="min-h-screen bg-slate-950 p-8 text-white">
      <section className="mx-auto max-w-5xl rounded-3xl border border-white/10 bg-white/[0.06] p-6">
        <p className="text-sm font-bold uppercase tracking-[0.2em] text-emerald-300">Student Project</p>
        <h1 className="mt-3 text-5xl font-black">Student Attendance Portal</h1>
        <p className="mt-3 text-slate-300">Mark attendance, review class presence, and prepare records.</p>
      </section>
    </main>
  );
}
`,
  '# Student Attendance Portal\n\nGenerated by FRIENDS.\n',
);

const genericFiles = baseNextFiles(
  'Custom Web App Starter',
  `export default function HomePage() {
  return (
    <main className="min-h-screen bg-slate-950 p-8 text-white">
      <section className="mx-auto max-w-5xl rounded-3xl border border-white/10 bg-white/[0.06] p-6">
        <h1 className="text-5xl font-black">Generated Project</h1>
        <p className="mt-3 text-slate-300">A runnable starter generated from your FRIENDS prompt.</p>
      </section>
    </main>
  );
}
`,
  '# Custom Web App Starter\n\nGenerated by FRIENDS.\n',
);

const bmiFiles = baseNextFiles(
  'BMI Calculator',
  `export default function HomePage() {
  return (
    <main className="min-h-screen bg-slate-950 p-8 text-white">
      <section className="mx-auto max-w-5xl rounded-3xl border border-white/10 bg-white/[0.06] p-6">
        <h1 className="text-5xl font-black">BMI Calculator</h1>
        <p className="mt-3 text-slate-300">Calculate BMI from height and weight inputs.</p>
      </section>
    </main>
  );
}
`,
  '# BMI Calculator\n\nGenerated by FRIENDS.\n',
);

export const templateRegistry: ProjectTemplate[] = [
  {
    id: 'ai_chatbot',
    name: 'AI Chatbot',
    intentProjectType: 'ai_chatbot_app',
    domain: 'conversational AI / chat interface',
    projectType: 'AI Tool',
    description: 'A standalone AI chatbot interface with message history, prompt suggestions, and mock assistant logic.',
    matchKeywords: ['ai chatbot', 'chatbot', 'chat bot', 'ai chat', 'assistant', 'chat assistant', 'conversational ai'],
    negativeKeywords: ['expense', 'ambulance', 'pdf', 'attendance'],
    features: [
      'Prompt input and send action',
      'Assistant and user message history',
      'Mock AI responses when no API key is configured',
      'Prompt suggestions',
      'Validation error for empty messages',
      'Responsive dark SaaS layout',
    ],
    components: ['Chatbot', 'ChatMessageList', 'PromptSuggestions'],
    logic: ['sendMessage()', 'createAssistantReply()', 'message history state', 'empty prompt validation'],
    forbiddenMistakes: [
      'Do not use Tailwind v3 PostCSS config with Tailwind v4',
      'Do not include ambulance, PDF notes, or expense tracker copy',
      'Do not overwrite the FRIENDS platform homepage',
    ],
    previewBullets: ['AI Chatbot', 'Prompt input and Send Message', 'Assistant message history', 'Prompt suggestions'],
    validation: {
      requiredFiles: ['components/Chatbot.tsx', 'components/ChatMessageList.tsx', 'components/PromptSuggestions.tsx', 'lib/mockAssistant.ts', 'types/chat.ts'],
      requiredText: ['AI Chatbot', 'Send Message', 'assistant', 'Prompt Suggestions'],
      forbiddenText: ['Ambulance Tracker', 'Expense Tracker', 'PDF Notes Converter'],
    },
    files: aiChatbotFiles,
  },
  {
    id: 'expense_tracker',
    name: 'Expense Tracker',
    intentProjectType: 'dashboard_app',
    domain: 'personal finance / expense tracking',
    projectType: 'Dashboard',
    description: 'A full personal finance dashboard for income, expenses, balance, transactions, and filters.',
    matchKeywords: ['expense tracker', 'expense', 'expenses', 'transaction', 'transactions', 'budget', 'spending', 'finance', 'income', 'balance'],
    negativeKeywords: ['ambulance', 'pdf', 'notes'],
    features: [
      'Add income and expense transactions',
      'Enter title, amount, category, date, and type',
      'View total income, total expenses, and current balance',
      'View recent transactions',
      'Filter transactions by type and category',
      'Delete transaction',
      'Show empty state and validation errors',
      'Use browser local state persistence when no database is requested',
    ],
    components: [
      'ExpenseTracker',
      'TransactionForm',
      'SummaryCards',
      'TransactionList',
      'TransactionItem',
      'CategoryFilter',
      'EmptyState',
      'Footer',
    ],
    logic: [
      'calculateIncome()',
      'calculateExpenses()',
      'calculateBalance()',
      'addTransaction()',
      'deleteTransaction()',
      'filterTransactions()',
    ],
    forbiddenMistakes: [
      'No ambulance content, map panel, ETA, or nearby ambulance copy',
      'No PDF upload or notes converter copy',
      'No generic add-item list',
      'No startup landing page pricing or testimonials unless explicitly asked',
      'Never overwrite app/page.tsx of the FRIENDS platform',
    ],
    previewBullets: ['Expense Tracker', 'Add Transaction', 'Income / Expense / Balance cards', 'Transaction list with filters'],
    validation: {
      requiredFiles: [
        'components/ExpenseTracker.tsx',
        'components/TransactionForm.tsx',
        'components/SummaryCards.tsx',
        'components/TransactionList.tsx',
        'lib/finance.ts',
        'types/finance.ts',
      ],
      requiredText: [
        'income',
        'expense',
        'balance',
        'transaction',
        'category',
        'amount',
        'add transaction',
        'delete transaction',
      ],
      forbiddenText: ['ambulance', 'ETA', 'nearby', 'PDF', 'notes converter', 'Add an item', 'Sample workflow item', 'startup landing page only'],
    },
    files: expenseFiles,
  },
  {
    id: 'ambulance_tracker',
    name: 'Ambulance Tracker',
    intentProjectType: 'location_tracking_app',
    domain: 'emergency dispatch / ambulance tracking',
    projectType: 'Functional Web App',
    description: 'A location-first ambulance availability and dispatch starter.',
    matchKeywords: ['ambulance', 'emergency', 'hospital', 'nearby ambulance', 'eta', 'dispatch'],
    negativeKeywords: ['expense', 'budget', 'pdf'],
    features: ['Nearby ambulance list', 'ETA and distance display', 'Availability status', 'Map panel'],
    components: ['AmbulanceTracker', 'AmbulanceList', 'MapPanel'],
    logic: ['Filter ambulances by area or ID', 'Show closest vehicles first', 'Surface status and ETA'],
    forbiddenMistakes: ['Do not include finance dashboard copy', 'Do not include PDF notes copy'],
    previewBullets: ['Ambulance Tracker', 'Map Panel', 'Nearby ambulance list', 'ETA and availability cards'],
    validation: {
      requiredFiles: ['components/AmbulanceTracker.tsx', 'components/MapPanel.tsx', 'lib/mockAmbulances.ts'],
      requiredText: ['ambulance', 'ETA', 'nearby', 'Map Panel'],
      forbiddenText: ['Expense Tracker', 'PDF Notes Converter'],
    },
    files: ambulanceFiles,
  },
  {
    id: 'pdf_to_notes_converter',
    name: 'PDF Notes Converter',
    intentProjectType: 'ai_tool',
    domain: 'document summarization / study notes',
    projectType: 'AI Tool',
    description: 'A standalone PDF/text-to-notes study tool generated as an exportable project.',
    matchKeywords: ['pdf', 'notes', 'summarize', 'study', 'document'],
    negativeKeywords: ['ambulance', 'expense'],
    features: ['Text input area', 'structured notes output', 'summary and key points'],
    components: ['PdfNotesConverter'],
    logic: ['Extract readable text', 'Create summary points', 'Prepare notes output'],
    forbiddenMistakes: ['Do not make this the FRIENDS homepage', 'Do not include ambulance or expense tracker copy'],
    previewBullets: ['PDF Notes Converter', 'Document text input', 'Generated Notes panel'],
    validation: {
      requiredFiles: ['components/PdfNotesConverter.tsx'],
      requiredText: ['PDF Notes Converter', 'Generated Notes'],
      forbiddenText: ['Ambulance Tracker', 'Expense Tracker'],
    },
    files: pdfFiles,
  },
  {
    id: 'attendance_portal',
    name: 'Student Attendance Portal',
    intentProjectType: 'student_dashboard_app',
    domain: 'education / attendance management',
    projectType: 'Student Project',
    description: 'A student attendance tracker with daily marking and class stats.',
    matchKeywords: ['attendance', 'student', 'class', 'portal', 'school', 'college'],
    features: ['Student roster', 'Present/absent toggles', 'Attendance percentage', 'Daily record view'],
    components: ['AttendancePortal'],
    logic: ['Toggle attendance state', 'Calculate attendance percentage'],
    forbiddenMistakes: ['Do not include ambulance, PDF, or finance template copy'],
    previewBullets: ['Student Attendance Portal', 'Attendance summary', 'Student records'],
    validation: {
      requiredFiles: ['app/page.tsx'],
      requiredText: ['Student Attendance Portal'],
      forbiddenText: ['Ambulance Tracker', 'PDF Notes Converter', 'Expense Tracker'],
    },
    files: attendanceFiles,
  },
  {
    id: 'bmi_calculator',
    name: 'BMI Calculator',
    intentProjectType: 'calculator_app',
    domain: 'health calculator',
    projectType: 'Functional Web App',
    description: 'A simple BMI calculator starter.',
    matchKeywords: ['bmi', 'body mass', 'health calculator', 'fitness'],
    features: ['Height and weight inputs', 'BMI calculation', 'Health category feedback'],
    components: ['BmiCalculator'],
    logic: ['Calculate BMI from height and weight', 'Map score to category'],
    forbiddenMistakes: ['Do not provide medical diagnosis'],
    previewBullets: ['BMI Calculator', 'Height and weight inputs', 'BMI result'],
    validation: {
      requiredFiles: ['app/page.tsx'],
      requiredText: ['BMI Calculator'],
      forbiddenText: ['Ambulance Tracker', 'PDF Notes Converter', 'Expense Tracker'],
    },
    files: bmiFiles,
  },
  {
    id: 'generic_web_app',
    name: 'Custom Web App Starter',
    intentProjectType: 'custom_app',
    domain: 'custom software',
    projectType: 'Functional Web App',
    description: 'A flexible starter for prompts that do not match a specific template.',
    matchKeywords: [],
    features: ['Responsive application shell', 'Primary action', 'Editable starter logic'],
    components: ['HomePage'],
    logic: ['Keep app state locally', 'Provide clear extension points'],
    forbiddenMistakes: ['Do not leave the project blank', 'Do not overwrite the FRIENDS platform'],
    previewBullets: ['Generated Project', 'Runnable starter', 'Editable source files'],
    validation: {
      requiredFiles: ['app/page.tsx', 'package.json'],
      requiredText: ['Generated Project'],
      forbiddenText: [],
    },
    files: genericFiles,
  },
];

export function getTemplateById(id: TemplateId) {
  return templateRegistry.find((template) => template.id === id) ?? templateRegistry[templateRegistry.length - 1];
}

export function selectTemplate(rawPrompt: string, requestedType: ProjectType = 'Auto-detect') {
  const prompt = rawPrompt.toLowerCase();

  if (/\b(ai chatbot|chatbot|chat bot|ai chat|chat assistant|conversational ai|assistant bot)\b/.test(prompt)) {
    return getTemplateById('ai_chatbot');
  }

  if (/\b(expense|expenses|transaction|transactions|budget|spending|finance|income|balance)\b/.test(prompt)) {
    return getTemplateById('expense_tracker');
  }

  const scored = templateRegistry
    .filter((template) => template.id !== 'generic_web_app')
    .map((template) => {
      const positive = template.matchKeywords.reduce((total, keyword) => total + (prompt.includes(keyword.toLowerCase()) ? 3 : 0), 0);
      const negative = (template.negativeKeywords ?? []).reduce((total, keyword) => total + (prompt.includes(keyword.toLowerCase()) ? 4 : 0), 0);
      return { template, score: positive - negative };
    })
    .sort((a, b) => b.score - a.score);

  const matched = scored[0];
  if (matched && matched.score > 0) {
    return matched.template;
  }

  if (requestedType !== 'Auto-detect') {
    return templateRegistry.find((template) => template.projectType === requestedType) ?? getTemplateById('generic_web_app');
  }

  return getTemplateById('generic_web_app');
}
